In [40]:
import numpy as np

Creating Arrays

In [41]:
a = [1, 2, 3, 4, 5]

In [42]:
arr1 = np.array(a)
arr1

array([1, 2, 3, 4, 5])

In [43]:
type(arr1)

numpy.ndarray

In [44]:
arr2 = np.arange(10, 20, 2.4)
arr2

array([10. , 12.4, 14.8, 17.2, 19.6])

In [45]:
arr3 = np.arange(1, 10).reshape(3, 3)
arr3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [46]:
arr3.size

9

In [47]:
arr3.ndim

2

In [48]:
arr3.dtype

dtype('int32')

In [49]:
arr3.max()

9

In [50]:
arr3.min()

1

In [51]:
arr3.sum()

45

In [52]:
arr3.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [53]:
arr3.prod()

362880

In [54]:
np.arange(1,9).reshape(2, 2, 2)

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [55]:
mat1 = np.arange(1, 9, dtype = np.float64 ).reshape(2, 2, 2)

In [56]:
mat1 = np.arange(1, 21).reshape(4, 5)
mat1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [57]:
mat1*2

array([[ 2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30],
       [32, 34, 36, 38, 40]])

In [58]:
mat1**3

array([[   1,    8,   27,   64,  125],
       [ 216,  343,  512,  729, 1000],
       [1331, 1728, 2197, 2744, 3375],
       [4096, 4913, 5832, 6859, 8000]], dtype=int32)

In [59]:
mat2 = mat1.flatten()
mat2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [60]:
mat2%2

array([1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0],
      dtype=int32)

In [61]:
b_arr = mat1 % 2 == 0
b_arr

array([[False,  True, False,  True, False],
       [ True, False,  True, False,  True],
       [False,  True, False,  True, False],
       [ True, False,  True, False,  True]])

In [62]:
mat1[b_arr]

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [63]:
mat1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [64]:
mat1[ mat1 % 5==0]

array([ 5, 10, 15, 20])

Indexing

In [68]:
mat1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [66]:
mat1[1, 3]

9

In [70]:
mat1[2,4]

15

In [73]:
mat1[ 1:3, 3]

array([ 9, 14])

In [79]:
mat1[1, 1:4]

array([7, 8, 9])

In [97]:
mat1[0:2, 1:6]


array([[ 2,  3,  4,  5],
       [ 7,  8,  9, 10]])

In [98]:
np.random.randint(1, 20, (10,10))

array([[ 7, 13, 17,  2,  1,  3, 11, 11, 19, 19],
       [16, 18,  3, 17, 14,  5, 12, 18,  3, 16],
       [ 7,  5, 16, 18,  4, 17, 12, 15,  9, 13],
       [ 5,  6, 19, 10, 12,  6,  5, 19,  4,  9],
       [10, 18, 17,  6,  9, 10, 13,  3, 15,  9],
       [12, 14,  4,  8,  1, 14,  7, 18, 18, 17],
       [15, 16, 10,  4, 12,  6,  7,  2,  1,  8],
       [16, 19,  9,  2, 12, 18, 13, 15, 14, 13],
       [13, 19,  6,  3, 16, 17,  2,  3,  8, 12],
       [ 4, 15,  5,  3, 15,  6,  1, 17,  7, 19]])

In [99]:
np.random.random((5, 5))

array([[0.9077747 , 0.56857278, 0.2038149 , 0.4430636 , 0.70894089],
       [0.48287087, 0.96072078, 0.97033235, 0.61352557, 0.63145787],
       [0.10640392, 0.78225539, 0.47734439, 0.12577325, 0.21837568],
       [0.18192642, 0.8172129 , 0.57997979, 0.93178777, 0.72902257],
       [0.52246246, 0.61108899, 0.73167719, 0.74259739, 0.13452506]])

In [101]:
mat2 = np.arange(1, 7).reshape(2, 3)

In [ ]:
mat3 = np.arange(1,7).reshape()

In [1]:
f = open('data/testoutput.txt')
f.write("Hello world!")
f.close()

FileNotFoundError: [Errno 2] No such file or directory: 'data/testoutput.txt'

In [4]:
numbers = [1, 2, 3, 4, 5]
print(min(numbers))
print(max(numbers))
print(sum(numbers))

1
5
15


In [5]:
numbers = [1, 2, 3, 4, 5]
doublenumbers = [number*2 for number in numbers]
print(doublenumbers)

[2, 4, 6, 8, 10]


In [9]:
s = "  strip me!"
print(s.strip())

strip me!


In [15]:
text = "Research has shown that it is often still possible to understand text even if all vowels are removed"
for vowel in ("a","i","e","o","u"):
    ____ = text.replace(vowel,"")
print(text)

Research has shown that it is often still possible to understand text even if all vowels are removed
